// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.2
// source: primeDecomposition.proto

package primeAPI

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DecompositeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *DecompositeRequest) Reset() {
	*x = DecompositeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primeDecomposition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecompositeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecompositeRequest) ProtoMessage() {}

func (x *DecompositeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_primeDecomposition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecompositeRequest.ProtoReflect.Descriptor instead.
func (*DecompositeRequest) Descriptor() ([]byte, []int) {
	return file_primeDecomposition_proto_rawDescGZIP(), []int{0}
}

func (x *DecompositeRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type DecompositeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []int32 `protobuf:"varint,1,rep,packed,name=results,proto3" json:"results,omitempty"`
}

func (x *DecompositeResponse) Reset() {
	*x = DecompositeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primeDecomposition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecompositeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecompositeResponse) ProtoMessage() {}

func (x *DecompositeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_primeDecomposition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecompositeResponse.ProtoReflect.Descriptor instead.
func (*DecompositeResponse) Descriptor() ([]byte, []int) {
	return file_primeDecomposition_proto_rawDescGZIP(), []int{1}
}

func (x *DecompositeResponse) GetResults() []int32 {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_primeDecomposition_proto protoreflect.FileDescriptor

var file_primeDecomposition_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22,
	0x2c, 0x0a, 0x12, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2f, 0x0a,
	0x13, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x32, 0x57,
	0x0a, 0x11, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x12, 0x42, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x65, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_primeDecomposition_proto_rawDescOnce sync.Once
	file_primeDecomposition_proto_rawDescData = file_primeDecomposition_proto_rawDesc
)

func file_primeDecomposition_proto_rawDescGZIP() []byte {
	file_primeDecomposition_proto_rawDescOnce.Do(func() {
		file_primeDecomposition_proto_rawDescData = protoimpl.X.CompressGZIP(file_primeDecomposition_proto_rawDescData)
	})
	return file_primeDecomposition_proto_rawDescData
}

var file_primeDecomposition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_primeDecomposition_proto_goTypes = []interface{}{
	(*DecompositeRequest)(nil),  // 0: api.DecompositeRequest
	(*DecompositeResponse)(nil), // 1: api.DecompositeResponse
}
var file_primeDecomposition_proto_depIdxs = []int32{
	0, // 0: api.PrimeDecompositor.Decomposite:input_type -> api.DecompositeRequest
	1, // 1: api.PrimeDecompositor.Decomposite:output_type -> api.DecompositeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_primeDecomposition_proto_init() }
func file_primeDecomposition_proto_init() {
	if File_primeDecomposition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_primeDecomposition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecompositeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primeDecomposition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecompositeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_primeDecomposition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_primeDecomposition_proto_goTypes,
		DependencyIndexes: file_primeDecomposition_proto_depIdxs,
		MessageInfos:      file_primeDecomposition_proto_msgTypes,
	}.Build()
	File_primeDecomposition_proto = out.File
	file_primeDecomposition_proto_rawDesc = nil
	file_primeDecomposition_proto_goTypes = nil
	file_primeDecomposition_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeDecompositorClient is the client API for PrimeDecompositor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeDecompositorClient interface {
	Decomposite(ctx context.Context, in *DecompositeRequest, opts ...grpc.CallOption) (*DecompositeResponse, error)
}

type primeDecompositorClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeDecompositorClient(cc grpc.ClientConnInterface) PrimeDecompositorClient {
	return &primeDecompositorClient{cc}
}

func (c *primeDecompositorClient) Decomposite(ctx context.Context, in *DecompositeRequest, opts ...grpc.CallOption) (*DecompositeResponse, error) {
	out := new(DecompositeResponse)
	err := c.cc.Invoke(ctx, "/api.PrimeDecompositor/Decomposite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimeDecompositorServer is the server API for PrimeDecompositor service.
type PrimeDecompositorServer interface {
	Decomposite(context.Context, *DecompositeRequest) (*DecompositeResponse, error)
}

// UnimplementedPrimeDecompositorServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeDecompositorServer struct {
}

func (*UnimplementedPrimeDecompositorServer) Decomposite(context.Context, *DecompositeRequest) (*DecompositeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decomposite not implemented")
}

func RegisterPrimeDecompositorServer(s *grpc.Server, srv PrimeDecompositorServer) {
	s.RegisterService(&_PrimeDecompositor_serviceDesc, srv)
}

func _PrimeDecompositor_Decomposite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecompositeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimeDecompositorServer).Decomposite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PrimeDecompositor/Decomposite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimeDecompositorServer).Decomposite(ctx, req.(*DecompositeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrimeDecompositor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PrimeDecompositor",
	HandlerType: (*PrimeDecompositorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Decomposite",
			Handler:    _PrimeDecompositor_Decomposite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "primeDecomposition.proto",
}
